<a href="https://colab.research.google.com/github/AlvinManoj05/Data-Preprocessing-Project/blob/main/Data_Processing_Group_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import Libraries

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Load Dataset

In [19]:
df=pd.read_csv("/content/istanbul_sales_data.csv")

## 3.Data Understanding

In [27]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I100001,C313884,Female,28.0,Clothing,2.0,600.16,Credit Card,2023-05-18,Istinye Park
1,I100002,C311565,Male,22.0,Technology,1.0,2100.00,Credit Card,2024-02-12,Zorlu Center
2,I100003,C366599,Male,20.0,Clothing,1.0,300.08,Cash,2023-09-11,Metrocity
3,I100004,C388172,Female,66.0,Books,5.0,75.75,Credit Card,2024-01-28,Metropol AVM
4,I100005,C389076,Female,53.0,Cosmetics,4.0,162.64,Cash,2023-10-24,Cevahir AVM

## 4.Missing Values Check

In [20]:
df.isna().sum()

invoice_no        0
customer_id       1
gender            1
age               1
category          1
quantity          1
price             1
payment_method    1
invoice_date      1
shopping_mall     1
dtype: int64

In [21]:
df.isna()/len(df)*100

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
499,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
500,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
501,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
502,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
503,0.0,0.198413,0.198413,0.198413,0.198413,0.198413,0.198413,0.198413,0.198413,0.198413