<a href="https://colab.research.google.com/github/AlvinManoj05/Data-Preprocessing-Project/blob/main/Data_Processing_Group_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import Libraries

In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Load Dataset

In [44]:
df=pd.read_csv("/content/istanbul_sales_data.csv")

## 3.Data Understanding

In [45]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I100001,C313884,Female,28.0,Clothing,2.0,600.16,Credit Card,2023-05-18,Istinye Park
1,I100002,C311565,Male,22.0,Technology,1.0,2100.00,Credit Card,2024-02-12,Zorlu Center
2,I100003,C366599,Male,20.0,Clothing,1.0,300.08,Cash,2023-09-11,Metrocity
3,I100004,C388172,Female,66.0,Books,5.0,75.75,Credit Card,2024-01-28,Metropol AVM
4,I100005,C389076,Female,53.0,Cosmetics,4.0,162.64,Cash,2023-10-24,Cevahir AVM

In [46]:
df.tail()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
499,I100500,C359469,Female,54.0,Clothing,2.0,600.16,Credit Card,2024-05-07,Istinye Park
500,I100501,C349248,Male,27.0,Souvenir,2.0,41.90,Credit Card,2023-04-18,Cevahir AVM
501,I100502,C319823,Female,41.0,Cosmetics,3.0,121.98,Debit Card,2024-10-13,Kanyon
502,I100503,C359037,Male,69.0,Food & Beverage,1.0,5.23,Cash,2023-09-29,Metropol AVM
503,```,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
# Shape
df.shape

(504, 10)

In [48]:
# Column names
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='object')

In [49]:
# Data types
df.dtypes

invoice_no         object
customer_id        object
gender             object
age               float64
category           object
quantity          float64
price             float64
payment_method     object
invoice_date       object
shopping_mall      object
dtype: object

In [50]:
#Complete information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      504 non-null    object
 1   customer_id     503 non-null    object
 2   gender          503 non-null    object
 3   age             503 non-null    float64
 4   category        503 non-null    object
 5   quantity        503 non-null    float64
 6   price           503 non-null    float64
 7   payment_method  503 non-null    object
 8   invoice_date    503 non-null    object
 9   shopping_mall   503 non-null    object
dtypes: float64(3), object(7)
memory usage: 39.5+ KB

In [51]:
# Basic statistics
df.describe()

              age    quantity         price
count  503.000000  503.000000    503.000000
mean    40.862823    2.697813   1206.421948
std     13.424982    1.321043   3064.507191
min     18.000000    1.000000      5.230000
25%     30.000000    2.000000     41.900000
50%     39.000000    2.000000    143.360000
75%     51.000000    4.000000    900.240000
max     72.000000    5.000000  26250.000000

In [52]:
#Numerical columns
df.select_dtypes(include="number").columns

Index(['age', 'quantity', 'price'], dtype='object')

In [53]:
#Categorical columns
df.select_dtypes(include="object").columns

Index(['invoice_no', 'customer_id', 'gender', 'category', 'payment_method',
       'invoice_date', 'shopping_mall'],
      dtype='object')